/// @file allowcontrol.hpp
/// @brief Header of AllowControl
/// @author Romain Ducher
///
/// @section LICENSE
///
/// Copyright 2012, 2013 Romain Ducher
///
/// This file is part of Reyn Tweets.
///
/// Reyn Tweets is free software: you can redistribute it and/or modify
/// it under the terms of the GNU Lesser General Public License as published by
/// the Free Software Foundation, either version 3 of the License, or
/// (at your option) any later version.
///
/// Reyn Tweets is distributed in the hope that it will be useful,
/// but WITHOUT ANY WARRANTY; without even the implied warranty of
/// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
/// GNU Lesser General Public License for more details.
///
/// You should have received a copy of the GNU Lesser General Public License
/// along with Reyn Tweets. If not, see <http://www.gnu.org/licenses/>.

#ifndef ALLOWCONTROL_HPP
#define ALLOWCONTROL_HPP

#include "genericcontrol.hpp"

/// @class AllowControl
/// @brief Control behind a LoginComponent
class AllowControl : public GenericControl
{
	Q_OBJECT

	public:
		/// @fn AllowControl();
		/// @brief Constructor
		AllowControl();

		/// @fn static void declareQML();
		/// @brief Declaring to the QML system
		static void declareQML();

		/// @fn Q_INVOKABLE void allowReynTweets();
		/// @brief Getting temporary tokens for the OAuth authentication flow.
		Q_INVOKABLE void allowReynTweets();

		/// @fn Q_INVOKABLE bool endAuth(QString postauthURL);
		/// @brief Finishing the authentication
		/// @param postauthURL URL after authenticating
		/// @return true if it is the very end, false if the app is still in the
		/// POST authorizing state.
		Q_INVOKABLE bool endAuth(QString postauthURL);

		/// @fn Q_INVOKABLE void getAccessTokens(QString verifier);
		/// @brief Getting the final OAuth tokens after user authorization
		/// (via the QML embedded browser)
		Q_INVOKABLE void getAccessTokens(QString verifier);


	signals:
		/// @fn void needVerifier(QString htmlPage, QString baseURL);
		/// @brief Signal after asking for OAuth Request Tokens suucessfully.
		///
		/// It sends the HTML page generated by Twitter for authorizing the app.
		/// @param htmlPage The HTML page for authorization.
		/// @param baseURL Base URL for loading the page
		void needVerifier(QString htmlPage, QString baseURL);


	protected slots:
		/// @fn void requestTokensOK(ProcessWrapper res);
		/// @brief Slot executed after getting OAuth Request tokens
		/// @param res The process result
		void requestTokensOK(ProcessWrapper res);

		/// @fn void accessTokensOK(ProcessWrapper res);
		/// @brief Slot executed after getting OAuth Access tokens
		/// @param res The process result
		void accessTokensOK(ProcessWrapper res);
};

#endif // ALLOWCONTROL_HPP
