#ifndef OAUTHUTILS_HPP
#define OAUTHUTILS_HPP

#include <QString>

/// @fn QString generateNonce();
/// @brief Generates a nonce for a request. To generate a nonce,
/// a random string is generated by taking 32 times one letter in the
/// alphabet. The letter could be in upper case or lower case. The final
/// nonce is the 64 base-encoding of the random string.
/// @return A nonce for a request.
QString generateNonce();

/// @fn QString generateTimestamp();
/// @brief Generates a timestamp for a request. The timestamp is the
/// number of seconds since the Unix Epoch (1/1/1970 at midnight).
/// @return A timestamp corresponding to the current date.
QString generateTimestamp();

/// @fn QByteArray hmacSha1(QByteArray key, QByteArray baseString);
/// @brief HMAC-SHA1 algorithm for signatures.
///
/// Its implementation for Reyn Tweets was found on the
/// <a href="http://qt-project.org">Qt Project website</a> here :
/// <a href="http://qt-project.org/wiki/HMAC-SHA1">
/// http://qt-project.org/wiki/HMAC-SHA1</a>.
/// @param key Key for signature
/// @param baseString String that we want to sign
/// @return The signature
QByteArray hmacSha1(QByteArray key, QByteArray baseString);

#endif // OAUTHUTILS_HPP
