/// @file reyntwittercalls.hpp
/// @brief Calls to Twitter
/// @author Romain Ducher

/*
Copyright 2011 Romain Ducher

This file is part of Reyn Tweets.

Reyn Tweets is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Reyn Tweets is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with Reyn Tweets.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef REYNTWITTERCALLS_HPP
#define REYNTWITTERCALLS_HPP

#include <QObject>
#include <QMap>
#include <QUuid>
#include <QWebView>
#include "resultwrapper.hpp"
#include "requests/genericrequester.hpp"

/// @class ReynTwitterCalls
/// @brief ReynTwitterCalls is a class which manages calls to Twitter. It is a
/// singleton. To use it
class ReynTwitterCalls : public QObject
{
	Q_OBJECT

	//////////////////////////////////
	// Core management of the class //
	//////////////////////////////////

	public:
		/// @fn ReynTwitterCalls();
		/// @brief Protected constructor
		ReynTwitterCalls(QObject & requester);

		/// @fn ~ReynTwitterCalls();
		/// @brief Destructor
		~ReynTwitterCalls();

	signals:
		/// @fn void sendResult(ResultSender res);
		/// @brief Signal emitted to the QObject that sends the request
		/// @param res Result of a request
		void sendResult(ResultWrapper res);

	public slots:
		/// @fn void endRequest();
		/// @brief Slot executed when a requester has finished its work
		void endRequest();

	protected:
		/// @brief QObject that asks for the request
		QObject & requestDemander;

		/// @brief Entity which manages requests that are running
		static QMap<QUuid, GenericRequester *> requesterManager;

		/// @brief OAuth information
		static OAuthManager oauthManager;

	private:
		/// @fn void addRequester(GenericRequester * requester);
		/// @brief Adding a requester to the requester manager
		/// @param requester Address of the requester
		void addRequester(GenericRequester * requester);

		/// @fn void removeRequester(GenericRequester * requester);
		/// @brief Removing a requester of the requester manager
		/// @param requester Address of the requester
		void removeRequester(GenericRequester * requester);

		/// @fn ResultSender buildResultSender(GenericRequester * endedRequest);
		/// @brief Method that builds the wrapper of a result
		/// @param endedRequest Ended request that contaons the result
		/// @return The wrapper of the request result
		ResultWrapper buildResultSender(GenericRequester * endedRequest);

		/// @fn inline void executeRequest(GenericRequester * requester);
		/// @brief Inline method for executing requests
		/// @param requester The requester
		inline void executeRequest(GenericRequester * requester);


	/////////////////////////////
	// Methods calling Twitter //
	/////////////////////////////

	public:
		//////////////
		// Searches //
		//////////////

		/// @fn void search(QString q);
		/// @brief Method that launch searches
		/// @param requestDemander QObject which asks for the request
		/// @param q The query
		void search(QString q);


		///////////
		// OAuth //
		///////////

		/// @fn void resetTokens();
		/// @brief Resetting the tokens. A full new OAuth authentication process
		/// has to be launch to get tokens and for authentication in requests
		void resetTokens();

		/// @fn void requestToken();
		/// @brief Method for getting a request token
		void requestToken();

		/// @fn void authorize(QWebView & browser);
		/// @brief Method for authorizing request Tokens
		/// @param requestDemander QObject which asks for the request
		/// @param browser View containing the Web page generated by Twitter
		void authorize(QWebView &browser);

		/// @fn void postAuthorize(QString login,
		///						   QString password,
		///						   QString denyString = "");
		/// @brief POST authorize() requests to allow or to deny the application.
		/// @param login User login, i.e. its username or its email
		/// @param password User password
		/// @param denyString String for denying the application
		void postAuthorize(QString login,
						   QString password,
						   QString denyString = "");

		/// @fn void accessToken();
		/// @brief Method for getting an access token
		void accessToken();
};

#endif // REYNTWITTERCALLS_HPP
