/// @file qmlapplicationviewer.hpp
/// @brief Header of QmlApplicationViewer
/// @author Romain Ducher
///
/// @section LICENSE
///
/// Copyright 2012 Romain Ducher
///
/// This file is part of Reyn Tweets.
///
/// Reyn Tweets is free software: you can redistribute it and/or modify
/// it under the terms of the GNU Lesser General Public License as published by
/// the Free Software Foundation, either version 3 of the License, or
/// (at your option) any later version.
///
/// Reyn Tweets is distributed in the hope that it will be useful,
/// but WITHOUT ANY WARRANTY; without even the implied warranty of
/// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
/// GNU Lesser General Public License for more details.
///
/// You should have received a copy of the GNU Lesser General Public License
/// along with Reyn Tweets. If not, see <http://www.gnu.org/licenses/>.
///
/// @section Notes
/// checksum 0x898f version 0x70013
///
/// This file was generated by the Qt Quick Application wizard of Qt Creator.
/// QmlApplicationViewer is a convenience class containing mobile device specific
/// code such as screen orientation handling. Also QML paths and debugging are
/// handled here.
/// It is recommended not to modify this file, since newer versions of Qt Creator
/// may offer an updated version of it.

#ifndef QMLAPPLICATIONVIEWER_HPP
#define QMLAPPLICATIONVIEWER_HPP

#include <QtDeclarative/QDeclarativeView>

/// @class QmlApplicationViewer
/// @brief QmlApplicationViewer is a convenience class containing mobile device specific
/// code such as screen orientation handling.
///
/// Also QML paths and debugging are handled here.
/// It is recommended not to modify this file, since newer versions of Qt Creator
/// may offer an updated version of it.
class QmlApplicationViewer : public QDeclarativeView
{
	Q_OBJECT

public:
	enum ScreenOrientation {
		ScreenOrientationLockPortrait,
		ScreenOrientationLockLandscape,
		ScreenOrientationAuto
	};

	explicit QmlApplicationViewer(QWidget *parent = 0);
	virtual ~QmlApplicationViewer();

	static QmlApplicationViewer *create();

	void setMainQmlFile(const QString &file);
	void addImportPath(const QString &path);

	// Note that this will only have an effect on Symbian and Fremantle.
	void setOrientation(ScreenOrientation orientation);

	void showExpanded();

private:
	class QmlApplicationViewerPrivate *d;
};

QApplication *createApplication(int &argc, char **argv);

#endif // QMLAPPLICATIONVIEWER_HPP
